### ISSUE TITLE
Download link

### ISSUE THREAD

**Issue by samhstn** [JMurphyWeb/gish#1]
I'd prefer to just run a command rather than having to copy and paste into a directory.

So [here](https://github.com/JMurphyWeb/gish/commit/5c0b2d5785a1e4fc9342663bc649229c2c9f51ee#diff-04c6e90faac2675aa89e2176d2eec7d8R51).

Perhaps consider a curl command, something like this: https://github.com/JMurphyWeb/gish/commit/5c0b2d5785a1e4fc9342663bc649229c2c9f51ee#diff-04c6e90faac2675aa89e2176d2eec7d8R51

**Comment by jay-meister** [comment]
@shouston3 yeah in the future it can be an npm module which you can install globally, or I like the idea of it being downloaded through curl.

Both your links seem to point to the same piece of the diff?

**Comment by jay-meister** [comment]
@shouston3 working on it now. npm i -g

**Comment by jay-meister** [comment]
updated master branch, will publish to npm to test

**Comment by jay-meister** [comment]
@shouston3 try `npm i gish-workflow -g`

**Comment by jay-meister** [comment]
remember to have a github access token to hand

**Comment by jay-meister** [comment]
getting started guides added to README

**Comment by samhstn** [comment]
Looks great 👍
