### ISSUE TITLE
Start issue should assign user to the issue

### ISSUE THREAD

**Issue by jay-meister** [JMurphyWeb/gish#2]
When a user types `gish start 2`, they should be assigned to it.

(going to use this issue for testing)

**Comment by jay-meister** [comment]
I have started work on 2 and it is going well

**Comment by jay-meister** [comment]
almost done..

**Comment by jay-meister** [comment]
Just tried gish end to remove my assignment

**Comment by jay-meister** [comment]
all seems to be working, `gish end` will now also remove your assignment

**Comment by samhstn** [comment]
Labels?

**Comment by jay-meister** [comment]
Not yet

**Comment by jay-meister** [comment]
MVPd
